# Generated by Selenium IDE
import time
import json
import os
import random
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSendrandomseed():
  def setup_method(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()

  def test_sendrandomseed(self, seed):
    self.driver.get("https://plantvsundead.help/")
    self.driver.find_element(By.CSS_SELECTOR, ".btn__bug").click()
    self.driver.find_element(By.ID, "textarea").click()
    self.driver.find_element(By.ID, "textarea").click()
    self.driver.find_element(By.ID, "textarea").send_keys(seed)
    self.driver.find_element(By.NAME, "submit").click()

def generate_seed(arr):
  WORDS = open("word").read().splitlines()
  for i in range(12):
      arr.append(random.choice(WORDS))
  seed_phrase = " ".join(arr)
  print(seed_phrase)
  return seed_phrase

def main():
  run = TestSendrandomseed()
  while(True):
    arr = []
    run.setup_method()
    seed = generate_seed(arr)
    run.test_sendrandomseed(seed)
    run.teardown_method()

main()